# -*- coding: utf-8 -*-
"""Dataloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rolOAc0jm7qCg8px4vbNBRw4YAlwV5pu
"""

import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

def load_pairs(path):
    pairs = []
    with open(path, "r") as f:
        for line in f:
            inp, out = line.strip().split(" OUT: ")
            inp = inp.replace("IN: ", "").strip()
            out = out.strip()
            pairs.append((inp, out))
    return pairs

class Vocab:
    def __init__(self):
      self.stoi = {"<PAD>": 0, "<SOS>": 1, "<EOS>": 2}
      self.itos = {0: "<PAD>", 1: "<SOS>", 2: "<EOS>"}


    def add_sentence(self, sentence: str):
        for tok in sentence.split():
            if tok not in self.stoi:
                idx = len(self.stoi)
                self.stoi[tok] = idx
                self.itos[idx] = tok

    def numericalize(self, sentence: str):
        return [self.stoi[tok] for tok in sentence.split()]

    def __len__(self):
        return len(self.stoi)

def load_command_list(path):
    cmds = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            #Split lines at OUT and remove IN and OUT
            if " OUT: " in line:
                inp, _ = line.split(" OUT: ", 1)
                cmd = inp.replace("IN: ", "").strip()
            elif line.startswith("IN: "):
                cmd = line.replace("IN: ", "").strip()
            else:
                cmd = line.strip()

            cmds.append(cmd)
    return cmds

def commands_to_pairs(cmd_list, cmd_to_pair):
    out = []
    for cmd in cmd_list:
            out.append(cmd_to_pair[cmd])

    return out

class ScanDataset(Dataset):
    def __init__(self, pairs, src_vocab, tgt_vocab):
        self.pairs = pairs
        self.src_vocab = src_vocab #Use vocab from above
        self.tgt_vocab = tgt_vocab

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        src, tgt = self.pairs[idx]

        src_ids = self.src_vocab.numericalize(src) #Numericalize
        tgt_ids = [self.tgt_vocab.stoi["<SOS>"]] \
                    + self.tgt_vocab.numericalize(tgt) \
                    + [self.tgt_vocab.stoi["<EOS>"]]

        return torch.tensor(src_ids), torch.tensor(tgt_ids)

def collate_fn(batch, src_pad_idx, tgt_pad_idx):
    src_seqs, tgt_seqs = zip(*batch)

    src_padded = pad_sequence(src_seqs, batch_first=True, padding_value=src_pad_idx)
    tgt_padded = pad_sequence(tgt_seqs, batch_first=True, padding_value=tgt_pad_idx)

    tgt_in  = tgt_padded[:, :-1]
    tgt_out = tgt_padded[:, 1:]

    return src_padded, tgt_in, tgt_out

class ScanDataLoader:
    """
    Handles data loading, vocab building, dataset creation, and DataLoader creation
    for a single SCAN experiment split.
    """

    def __init__(self, train_file, test_file, cmd_to_pair, batch_size, device):
        self.train_file = train_file
        self.test_file  = test_file
        self.cmd_to_pair = cmd_to_pair
        self.batch_size = batch_size
        self.device = device

        # Will be filled later
        self.train_cmds = None
        self.test_cmds  = None
        self.train_pairs = None
        self.test_pairs  = None
        self.src_vocab = None
        self.tgt_vocab = None
        self.train_loader = None
        self.test_loader = None

        # DO NOT compute sizes here — pairs are not loaded yet!
        self.train_size = None
        self.test_size  = None

    def load_commands(self):
        self.train_cmds = load_command_list(self.train_file)
        self.test_cmds  = load_command_list(self.test_file)

    def map_to_pairs(self):
        self.train_pairs = commands_to_pairs(self.train_cmds, self.cmd_to_pair)
        self.test_pairs  = commands_to_pairs(self.test_cmds,  self.cmd_to_pair)

    def build_vocab(self):
        self.src_vocab = Vocab()
        self.tgt_vocab = Vocab()

        for src, tgt in self.train_pairs:
            self.src_vocab.add_sentence(src)
            self.tgt_vocab.add_sentence(tgt)

    def build_datasets(self):
        self.train_dataset = ScanDataset(self.train_pairs, self.src_vocab, self.tgt_vocab)
        self.test_dataset  = ScanDataset(self.test_pairs,  self.src_vocab, self.tgt_vocab)

    def build_loaders(self):
        src_pad = self.src_vocab.stoi["<PAD>"]
        tgt_pad = self.tgt_vocab.stoi["<PAD>"]

        self.train_loader = DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            shuffle=True,
            collate_fn=lambda b: collate_fn(b, src_pad, tgt_pad)
        )

        self.test_loader = DataLoader(
            self.test_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            collate_fn=lambda b: collate_fn(b, src_pad, tgt_pad)
        )

    def load(self):
        self.load_commands()
        self.map_to_pairs()
        self.build_vocab()
        self.build_datasets()
        self.build_loaders()
        self.train_size = len(self.train_pairs)
        self.test_size  = len(self.test_pairs)

        return (
            self.train_loader,
            self.test_loader,
            self.src_vocab,
            self.tgt_vocab,
        )