# -*- coding: utf-8 -*-
"""Decoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYK0r2YXm7rIOy77Ly9HWYkgqonXsm5f
"""

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def greedy_decode(
    model,
    src,
    sos_idx,
    eos_idx,
    max_len=60,
    oracle_length=None,
    forbid_eos=False,
    device=device,
):

    model.eval()
    src = src.to(device)
    batch_size = src.size(0)

    ys = torch.full((batch_size, 1), sos_idx, dtype=torch.long, device=device)
    finished = torch.zeros(batch_size, dtype=torch.bool, device=device)

    with torch.no_grad():
        steps = oracle_length if oracle_length is not None else max_len

        for _ in range(steps):
            logits = model(src, ys)          # (B, cur_len, V)
            next_logits = logits[:, -1, :]   # (B, V)

            if forbid_eos:
                next_logits[:, eos_idx] = -1e9

            next_tok = next_logits.argmax(dim=-1)  # (B,)
            ys = torch.cat([ys, next_tok.unsqueeze(1)], dim=1)

            if oracle_length is None:  # normal mode: stop when all hit EOS
                finished |= (next_tok == eos_idx)
                if finished.all():
                    break

        # Oracle mode: for experiment 2
        if oracle_length is not None and not forbid_eos:
            eos_col = torch.full((batch_size, 1), eos_idx, dtype=torch.long, device=device)
            ys = torch.cat([ys, eos_col], dim=1)

    # Drop SOS and truncate at EOS per sequence
    preds = []
    for seq in ys[:, 1:].tolist():
        if eos_idx in seq:
            seq = seq[:seq.index(eos_idx)]
        preds.append(seq)
    return preds