# -*- coding: utf-8 -*-
"""Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hafX_9Fzn6Oe9xZZz5wIxawvj9T_ad5-
"""

def _strip_sequence(seq, pad_idx, eos_idx):
    """Remove PAD, cut at EOS"""
    out = []
    for idx in seq:
        if idx == eos_idx:
            break
        if idx == pad_idx:
            continue
        out.append(idx)
    return out

def sequence_accuracy(pred_indices, gold_indices, pad_idx, eos_idx):
    p = _strip_sequence(pred_indices, pad_idx, eos_idx)
    g = _strip_sequence(gold_indices, pad_idx, eos_idx)
    return 1.0 if p == g else 0.0

def token_accuracy(pred_indices, gold_indices, pad_idx, eos_idx):
    # Clean gold
    gold = []
    for t in gold_indices:
        if t == eos_idx:
            break
        if t != pad_idx:
            gold.append(t)

    correct = 0
    total = len(gold)

    # Compare only positions in gold
    for i, g in enumerate(gold):
        if i < len(pred_indices) and pred_indices[i] == g:
            correct += 1

    # If prediction shorter: missing tokens count as incorrect implicitly
    return correct, total

def token_accuracy_exp1(pred_indices, gold_indices, pad_idx, eos_idx):

    p = _strip_sequence(pred_indices, pad_idx, eos_idx)
    g = _strip_sequence(gold_indices, pad_idx, eos_idx)

    min_len = min(len(p), len(g))
    correct = sum(p[i] == g[i] for i in range(min_len))

    return correct, min_len